---
- name: Install Flatpak Applications on Fedora Silverblue
  hosts: personal
  become: yes  # This is important to execute with elevated privileges
  tasks:
    - name: Install Discord Flatpak
      flatpak:
        name: com.discordapp.Discord
        state: present
        remote: flathub
        method: user

    - name: Install Obsidian Flatpak
      flatpak:
        name: md.obsidian.Obsidian
        state: present
        remote: flathub
        method: user

    # - name: Reboot if required by RPM-OSTree
    #   command: systemctl reboot
    #   when: ostree_reboot_pending.stdout == "true"
    #   register: ostree_reboot_pending
    #   changed_when: false
