---
- name: Create Ubuntu distrobox 
  command: >
    distrobox create -i ubuntu --nvidia

- name: Run Ubuntu container
  containers.podman.podman_container:
    name: Ubuntu
    timezone:
      name: en_US # not required. Name of the timezone for the system clock. Default is to keep current setting. B(At least one of name and hwclock are required.)
      hwclock: local # not required. choices: local;UTC. Whether the hardware clock is in UTC or in local timezone. Default is to keep current setting. Note that this option is recommended not to change and may fail to configure, especially on virtual environments such as AWS. B(At least one of name and hwclock are required.) I(Only used on Linux.)
    state: started

- name: Install orcaslicer deps
  command: >
    podman exec ubuntu apt install libgstvideo-1.0 libgstreamer1.0-0 libgtk-3-0 libfontconfig fuse webkit2gtk-driver libwebkit2gtk-4.0-37 -y


