---
- name: Create Ubuntu distrobox 
  command: >
    distrobox create -i ubuntu --nvidia

- name: Run Ubuntu container
  containers.podman.podman_container:
    name: Ubuntu
    image: ubuntu
    timezone: en_US 
    state: started

- name: Install orcaslicer deps
  command: >
    podman exec ubuntu apt install libgstvideo-1.0 libgstreamer1.0-0 libgtk-3-0 libfontconfig fuse webkit2gtk-driver libwebkit2gtk-4.0-37 -y


