---
# Not needed
# - name: Create AppImage install directory
#   file:
#     path: "{{ appimage_install_dir }}"
#     state: directory
#   become: true

- name: Download and install AppImages
  uri:
    url: "{{ item.url }}"
    dest: "{{ appimage_install_dir }}/{{ item.name }}.AppImage"
    headers:
      User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0
    method: GET
    owner: pj
    group: pj
    mode: u=rwx,g=r,o=r
    force: true
    status_code: [200, 304]
  loop: "{{ appimages }}"
  register: downloaded_appimages
  become: true

- name: Download Appimages pngs
  get_url:
    url: "{{ item.image_url }}"
    dest: "{{ appimage_install_dir }}/{{ item.name }}.{{ item.image_format }}"
    headers:
      User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0
    owner: pj
    group: pj
    mode: u=rw,g=r,o=r 
    force: true
  loop: "{{ appimages }}"
  become: true

- name: Template Desktop Files
  template:
    src: roles/Appimages/templates/app_template.desktop.j2
    dest: "{{ appimage_install_dir }}/{{ item.item.name }}.desktop"
    owner: pj
    group: pj
    mode: u=rw,g=r,o=r
  vars:
    name: "{{ item.item.name }}"
    image_format: "{{ item.item.image_format }}"
  loop: "{{ downloaded_appimages.results }}"