---
- name: Install Layered Packages on Fedora Silverblue
  hosts: personal
  become: yes
  tasks:
    # - name: Download Brave Browser repo config
    #   get_url:
    #     url: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    #     dest: /tmp/
    #   register: download_result
      
    # - name: Copy Brave Browser repo file
    #   copy:
    #     src: "/tmp/brave-browser.repo"
    #     dest: "/etc/yum.repos.d/brave-browser.repo"
    #     remote_src: true
    #     mode: '644'
    #     owner: root
    #     group: root
    #   become: yes
    #   # become_user: pj
    #   when: download_result
    - name: Creating an empty file
      file:
        path: /etc/yum.repos.d/brave-browser.repo
        state: touch
        
    - name: Creating an empty file
      file:
        path: /etc/yum.repos.d/asus.repo
        state: touch


    - name: Add Brave repo
      blockinfile: 
        state: present
        insertafter: EOF
        dest: /etc/yum.repos.d/brave-browser.repo
        # marker: "<!-- add services ANSIBLE MANAGED BLOCK -->"
        content: |
          [brave-browser]
          name=Brave Browser
          enabled=1
          autorefresh=1
          baseurl=https://brave-browser-rpm-release.s3.brave.com/$basearch
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

    - name: Add Asus Linux repo
      blockinfile: 
        state: present
        insertafter: EOF
        dest: /etc/yum.repos.d/asus.repo
        # marker: "<!-- add services ANSIBLE MANAGED BLOCK -->"
        content: |
          [copr:copr.fedorainfracloud.org:lukenukem:asus-linux]
          name=Copr repo for asus-linux owned by lukenukem
          baseurl=https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/fedora-$releasever-$basearch/
          type=rpm-md
          skip_if_unavailable=True
          gpgcheck=1
          gpgkey=https://download.copr.fedorainfracloud.org/results/lukenukem/asus-linux/pubkey.gpg
          repo_gpgcheck=0
          enabled=1
          enabled_metadata=1
      
    - name: Install apps
      community.general.rpm_ostree_pkg:
        name: 
          - brave-browser
          - asusctl
          - supergfxctl
        state: present
      become: yes
      
