---
- name: Add Flatpak repositories
  flatpak_remote:
    name: "{{ item.label }}"
    flatpakrepo_url: "{{ item.url }}"
    state: present
    method: user
  loop: "{{ flatpack_repos }}"

- name: Install Discord Flatpak
  flatpak:
    name: "{{ item.pkg }}"
    state: present
    remote: "{{ item.repo }}"
    method: user
  loop: "{{ flatpacks_to_install }}"
